-- Users Table
CREATE TABLE IF NOT EXISTS users (
    user_id TEXT PRIMARY KEY,
    username TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Tickets Table
CREATE TABLE IF NOT EXISTS tickets (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES users(user_id) ON DELETE SET NULL,
    channel_id TEXT,
    category TEXT,
    topic TEXT,
    description TEXT,
    claimed_by TEXT,
    status TEXT DEFAULT 'open',
    rating INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP WITH TIME ZONE,
    first_response_at TIMESTAMP WITH TIME ZONE
);

-- Messages Table (Log)
CREATE TABLE IF NOT EXISTS messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT REFERENCES tickets(ticket_id) ON DELETE CASCADE,
    author_id TEXT,
    content TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Admin Notes Table
CREATE TABLE IF NOT EXISTS notes (
    note_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT REFERENCES tickets(ticket_id) ON DELETE CASCADE,
    admin_id TEXT,
    note_content TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Guild Configs Table
CREATE TABLE IF NOT EXISTS guild_configs (
    guild_id TEXT PRIMARY KEY,
    tech_category_id TEXT,
    admin_category_id TEXT,
    general_category_id TEXT,
    support_role_id TEXT,
    log_channel_id TEXT,
    tech_welcome TEXT DEFAULT 'مرحباً بك في قسم الدعم الفني',
    admin_welcome TEXT DEFAULT 'مرحباً بك في قسم الإدارة',
    general_welcome TEXT DEFAULT 'مرحباً بك في قسم الاستفسارات العامة',
    alert_hours INTEGER DEFAULT 24,
    rate_limit_enabled INTEGER DEFAULT 0,
    max_tickets_per_day INTEGER DEFAULT 3
);

-- Saved Replies Table
CREATE TABLE IF NOT EXISTS saved_replies (
    reply_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT,
    trigger TEXT,
    content TEXT,
    created_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Ticket Attachments Table
CREATE TABLE IF NOT EXISTS ticket_attachments (
    attachment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT REFERENCES tickets(ticket_id) ON DELETE CASCADE,
    url TEXT,
    filename TEXT,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Support Points Table
CREATE TABLE IF NOT EXISTS support_points (
    user_id TEXT,
    guild_id TEXT,
    total_points INTEGER DEFAULT 0,
    tickets_closed INTEGER DEFAULT 0,
    average_rating REAL DEFAULT 0,
    PRIMARY KEY (user_id, guild_id)
);

-- Welcome Configuration Table
CREATE TABLE IF NOT EXISTS welcome_config (
    guild_id TEXT PRIMARY KEY,
    channel_id TEXT,
    message TEXT DEFAULT 'مرحباً {user} في {server}! 🎉',
    enabled BOOLEAN DEFAULT true
);

-- Disable Row Level Security (RLS) for all tables
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE tickets DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE guild_configs DISABLE ROW LEVEL SECURITY;
ALTER TABLE saved_replies DISABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_attachments DISABLE ROW LEVEL SECURITY;
ALTER TABLE support_points DISABLE ROW LEVEL SECURITY;
ALTER TABLE welcome_config DISABLE ROW LEVEL SECURITY;
